# Generated by Django 2.2.6 on 2022-03-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordform', models.CharField(max_length=50, verbose_name='Словоформа в корпусе')),
                ('form1', models.CharField(max_length=50, verbose_name='Форма 1')),
                ('form2', models.CharField(max_length=50, verbose_name='Форма 2')),
                ('form3', models.CharField(max_length=50, verbose_name='Форма 3')),
                ('form4', models.CharField(max_length=50, verbose_name='Форма 4')),
                ('var_type', models.CharField(max_length=10, verbose_name='Вариативность типа')),
                ('notes', models.TextField(verbose_name='Пометки')),
                ('morph', models.CharField(max_length=30, verbose_name='Морфема')),
                ('pos', models.CharField(max_length=30, verbose_name='Часть речи')),
                ('morph_feats', models.TextField(verbose_name='Морфологические признаки')),
                ('freq_or', models.IntegerField(verbose_name='ABS (устный корпус)')),
                ('ipm_or', models.FloatField(blank=True, null=True, verbose_name='IPM (устный корпус)')),
                ('freq_main', models.IntegerField(verbose_name='ABS (основной корпус)')),
                ('ipm_main', models.FloatField(blank=True, null=True, verbose_name='IPM (основной корпус)')),
                ('source', models.TextField(verbose_name='Источник')),
            ],
        ),
    ]
