# Generated by Django 2.2.6 on 2022-03-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Словоформа', 'verbose_name_plural': 'Словоформы'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='form1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма 1'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='form2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма 2'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='form3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма 3'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='form4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Форма 4'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='freq_main',
            field=models.IntegerField(blank=True, null=True, verbose_name='ABS (основной корпус)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='freq_or',
            field=models.IntegerField(blank=True, null=True, verbose_name='ABS (устный корпус)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='morph',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Морфема'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='morph_feats',
            field=models.TextField(blank=True, null=True, verbose_name='Морфологические признаки'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Пометки'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pos',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Часть речи'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='var_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Вариативность типа'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wordform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Словоформа в корпусе'),
        ),
    ]
